### PR TITLE
test

### PR DESCRIPTION
**Pull request by U1F605**

### CODE REVIEW

**Comment by Gherkashen2** [comment]
My socks5 has no issue with Anxray but with your client does not work!

**Comment by Gherkashen2** [comment]
[Matsuri 5743441201193059638.log](https://github.com/U1F605/vmessocketForAndroid/files/8694577/Matsuri.5743441201193059638.log)

**Comment by Gherkashen2** [comment]
[AnXray 8195926084881976858.log](https://github.com/U1F605/vmessocketForAndroid/files/8694581/AnXray.8195926084881976858.log)

**Comment by U1F605** [comment]
> My socks5 has no issue with Anxray but with your client does not work!... now I'm gonna send log files of your client and anxray here:

what kind of protocol did you use?

**Pull request closed without merging**
