### PR TITLE
Update debug.yml

### PR DESCRIPTION
**Pull request by U1F605**

### CODE REVIEW

**Comment by Shikopat** [comment]
IT CAN BE CONNECTED :

LibCore Not Support!

**Comment by U1F605** [comment]
> Your app uses too much battery more than main "matsuri"

well, it is debug edition
you could build the release edition

**Comment by U1F605** [comment]
> Your app uses too much battery more than main "matsuri"

well, it is debug edition
you could build the release edition

**Comment by Gherkashen2** [comment]
I'm not developer but I like your fork

**Pull request merged**
